server:
  port: 8081

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiangcun?useUnicode=true&characterEncoding=utf8
    username: root
    password: 19720603

  redis:
    host: 192.168.234.128
    port: 6124
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10
        time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

  servlet:
    multipart:
      max-request-size: 5GB #上传文件总的最大值 默认10MB
      max-file-size: 1GB #单个文件的最大值，默认10MB
  #图片上传的位置
  web:
    resources:
      static-locations: classpath:/static

# 验证码配置
kaptcha:
  border: "no"         #  是否有边框，默认为 yes，可选 yes、no
  border.color: 105,179,90    # 边框颜色
  textproducer:
    font:
      color: blue     # 验证码字体颜色
      size: 30        # 文本字符大小
      names: 宋体,楷体     # 文本字体样式
    char:
      length: 4     # 验证码文本字符长度
  image:
    width: 120      # 图片宽度
    height: 40      # 图片高度
  session:
    key: code     # 存储 session key


mybatis:
  configuration:
    map-underscore-to-camel-case: true



mybatis-plus:
  type-aliases-package: com.wen # 别名扫描包
logging:
  level:
    com.wen: debug


#上传到服务端的图片文件夹
# dev开发环境
photo:
  file:
    dir: D:\peng\code\Project\ShuZhi\ShuZhiXC\src\main\resources\static\imgs


# 上线环境
#photo:
#  file:
#    dir: /tmp/images/shuzhi









